version: "3.9"
services:
  app:
    build: .
    image: chatgpt-clone-server
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - chatgpt-network
  redis:
    image: "redis:latest"
    container_name: chatgpt-clone-redis
    ports:
      - "6380:6379"
    networks:
      - chatgpt-network

networks:
  chatgpt-network:
